easy_admin:
    design:
        menu:
            - label: 'Where I Go'
              icon: 'newspaper-o'
              children:
                  - {entity: 'Category', icon: book, label: 'Catégories'}
                  - {entity: 'PlaceHasCategory', icon: plane-departure, label: 'Catégories associées aux endroits'}
                  - {entity: 'Place', icon: map-marker, label: 'WIG'}
                  - {entity: 'Picture', icon: images, label: 'Photos'}
                  - {entity: 'Background', icon: image, label: 'Images de fond'}
                  - {entity: 'Booking', icon: bookmark, label: 'Réservations'}
